<a href="https://colab.research.google.com/github/jarvismayur/Deep-Learning-With-PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is the PyTorch?
PyTorch is an open Source machine learning and deep learning framework.






## What can PyTorch be used for ?

PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.




## Who is in the PyTorch?

Many of the world's largest companies such as Meta ( Facebook ). Tesla and Microsoft as well as artificial intelligence research companies such as OpenAI use PyTorch to power research and machine learning to thier products.



## Why use PyTorch ?

Machine Learning researchers love using PyTorch. And as of February 2022, PyTorch is the most used deep learning framework of Paper With Code, a website for tracking machine learing research papers and the code repositories attached with them.

PyTorch also helps take care of many things such as GPU acceleration behind the scences.

So you can focus on manipulating data and writing algorithms and PyTorch will make sure it runs fast.



# Algerbric Objects

In mathematics, algebraic objects are fundamental structures that exhibit algebraic properties and operations.
There are different algebraic objects which are listed below


* Scaler
* Vector
* Matrix
* Tensor







# Introduction To Tensors



## Tensors

In mathematics, a tensor is an algebraic object that describes a multilinear relationship between sets of algebraic objects related to a vector space. Tensors may map between different objects such as vectors, scalars, and even other tensors. [Wikipedia](https://en.wikipedia.org/wiki/Tensor#:~:text=In%20mathematics%2C%20a%20tensor%20is,scalars%2C%20and%20even%20other%20tensors.)

Tensors are fundamental building block of machine learning.



### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [7]:
# Importing the libraries for the Torch Assignments

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
print(torch.__version__)

2.3.0+cu121


In [9]:
# Scaler

scaler = torch.tensor(7)

In [10]:
scaler

tensor(7)

In [11]:
scaler.ndim # ndim properties gives the dimension of the objects that we are using

0

In [12]:
# Get tensor back as python int
scaler.item()

7

In [13]:
# Vector
vector = torch.tensor([7,7])

In [14]:
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [18]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [23]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensors

### Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with  random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html



In [26]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)

In [27]:
random_tensor

tensor([[0.1969, 0.7714, 0.1345, 0.6597],
        [0.0453, 0.3355, 0.4085, 0.5965],
        [0.2959, 0.4826, 0.8060, 0.9689]])

In [28]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))

In [29]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zero and ones

In [30]:
# Create a tensor of all zero
zeros = torch.zeros(size=(3,4))

In [31]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# Create a tensor with all ones
ones = torch.ones(size=(3,4))

In [33]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype # dtype is gives back the data types of the tensor

torch.float32

In [35]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like



In [36]:
# Use torch.range() and get deprecated message, use the torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)

In [37]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [39]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

Note: Tensor datatypes is one of the 8 big erros you'll into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing :  https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value

In [40]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor ( e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # weather or not to track gradients with this tensors operations

In [41]:
float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [44]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)

In [47]:
int_32_tensor

tensor([3, 6, 9])

In [48]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors ( tensor attributes )

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [49]:
# Create a tensor
some_tensor = torch.rand(3,4)

In [50]:
some_tensor

tensor([[0.0262, 0.0374, 0.1307, 0.5583],
        [0.4076, 0.3959, 0.0898, 0.0867],
        [0.7923, 0.7509, 0.1750, 0.2227]])

In [51]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: { some_tensor.dtype}")
print(f"Shape of tensor : { some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.0262, 0.0374, 0.1307, 0.5583],
        [0.4076, 0.3959, 0.0898, 0.0867],
        [0.7923, 0.7509, 0.1750, 0.2227]])
Datatype of tensor: torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


## Manipulating Tensors ( tensor operations )

Tensor operations include:

* Addition
* Substraction
* Multiplication ( element-wise )
* Division
* Martix multiplication

In [52]:
# Create a tensor and add 10 to it.
tensor = torch.tensor([1,2,3])

In [53]:
tensor+10

tensor([11, 12, 13])

In [54]:
# Multiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [55]:
tensor

tensor([1, 2, 3])

In [56]:
# Substract 10
tensor -10

tensor([-9, -8, -7])

## Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learing:
1. Element-wise multiplication
2. Matrix multiplication ( dot product )

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

there are atow main rules that performing matrix multitplication needs to satisfy

1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2 ,3) -> (3, 3)`


In [57]:
# Element wise multiplication
print(tensor, "*", tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [58]:
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [59]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [60]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.64 ms, sys: 1.1 ms, total: 3.74 ms
Wall time: 6.98 ms


In [61]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.22 ms, sys: 828 µs, total: 2.05 ms
Wall time: 10.3 ms


tensor(14)

## One of the most comman errors in deep learning : shape errors

In [62]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [64]:
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alais for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [65]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [66]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

## Transpose

To fix our tensor shape issues, we can manipulate the shape of one of the our tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [67]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [68]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [69]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f" New shapes : tensor_A = {tensor_A.shape} ( shaoe shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape } @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n ")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
 New shapes : tensor_A = torch.Size([3, 2]) ( shaoe shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 
 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc ( tensor aggregation )



In [70]:
# create a tensor
x = torch.arange(1,100,10)

In [71]:
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [72]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [73]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [74]:
# find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [75]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [76]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [77]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the min value occurs
x.argmin()

tensor(0)

In [78]:
x[0]

tensor(1)

In [79]:
# find the position in tensor that has maximun value with argmax()
x.argmax()

tensor(9)

In [80]:
x[9]

tensor(91)

## Reshaping, Stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes input tensor to  a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginial tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side ( hstack)
* Squeeze - removes all 1 dimension to a target tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [81]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)


In [82]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [83]:
# Add an extra deminsion
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [84]:
z = x.view(1,9)

In [85]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [86]:
z[:,0] = 5


In [87]:
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [88]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)

In [89]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [90]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

# Remove the extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor : {x_squeezed}")
print(f"\n New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

 New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

 New shape: torch.Size([9])


In [91]:
# torch.unsqueeze() - adds a single dimension to a target at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n New tensor: {x_unsqueezed}")
print(f"\n New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

 New shape: torch.Size([1, 9])


In [92]:
# torch.permute - rearranges the demisions of a target tensor in a specified order
x_original= torch.rand(size=(224, 224,3)) # [ height, width, color_channels]

# Permute  the original tensor to rearrange the axis (or dim) order
x_permuated = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape : {x_original.shape}")
print(f"New shape: {x_permuated.shape}") #[ colour_channels, height,widht]


Previous shape : torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [93]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuated[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing Tensor ( Selecting the Data from Tensor )

Indexing with PyTorch is similar to indexing with NumPy


In [94]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)


In [95]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [96]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [97]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [98]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [99]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [100]:
# Get all values of  0th and 1st deminsions but only index 1 of 2nd dimension
x[:, :,1]

tensor([[2, 5, 8]])

In [101]:
# Get all values of the 0 dimension but only the 1 index of the 2nd dimension
x[:, 1,1]

tensor([5])

In [102]:
# Get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0, 0,:]

tensor([1, 2, 3])

In [103]:
# Index on x to return 9
print(x[0][2][2])

tensor(9)


In [104]:
# Index on x to return 3,6,9
print(x[:,:, 2])

tensor([[3, 6, 9]])


# Pytorch Tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()


In [105]:
 # NumPy array to tensor

 array = np.arange(1.0, 8.0)
 tensor = torch.from_numpy(array) # warning : when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
 array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [106]:
# change the value of array. what will do to `tensor`?
array = array + 1

In [107]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [108]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [109]:
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility ( trying to take random out of random )
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ... `

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentailly what the random seed does is "flavour" the randomness.

Extra Resources for Reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [110]:
# Create a two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6276, 0.6387, 0.2622, 0.5582],
        [0.3590, 0.5799, 0.3235, 0.9469],
        [0.1410, 0.3515, 0.5651, 0.2213]])
tensor([[0.7948, 0.9675, 0.9806, 0.2105],
        [0.1384, 0.8069, 0.7621, 0.1968],
        [0.2864, 0.9182, 0.7935, 0.3038]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [111]:
# Let's make some random but reporducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU's ( and making faster computations )

GPU's  = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory ( good ).
### Getting a GPU
1. Easiest - Use Google Colab for free GPU (options to upgrade as well )
2. Use your own GPu - takes a little bit of setup and requieres the investment of purchasing a GPU, there are lot of options, See this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent compters on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) Takes a little bit of setting up to do this refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/



In [112]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Check for GPU access with PyTorch

In [113]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best pratice to setup device agnostic code : https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [114]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [115]:
device

'cpu'

In [116]:
# Count number of devices
torch.cuda.device_count()

0

## Putting tensors ( and models ) on the GPU

The reason we want our tensors / models on the GPU is because using a GPU results in faster Computations.



In [117]:
# Create a tensor ( default on the CPU )
tensor  = torch.tensor([1,2,3])

In [118]:
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [119]:
#  Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)

In [120]:
tensor_on_gpu

tensor([1, 2, 3])

## Moving tensor back to CPU


In [121]:
tensor_on_gpu.numpy()

array([1, 2, 3])

In [122]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

In [123]:
tensor_back_on_cpu

array([1, 2, 3])

In [124]:
tensor_on_gpu

tensor([1, 2, 3])